#!/bin/bash
 
 cd ~/Documents
  url=$(pbpaste)
   
   if [ -z "$url" ]; then
	        echo "Aucune URL trouvee dans le presse-papiers"
		     echo ""
		          read -p "Tape l'URL manuellement: " url
			   fi
			    
			    if [ -z "$url" ]; then
				         echo "ERREUR: Aucune URL fournie"
					      exit 1
					       fi
					        
					        clear
						 
						 echo ""
						  echo ""
						   echo "DIRECT LINK EXTRACTING"
						    echo ""
						     echo ""
						      echo "→  🎬  A  →  Movie"
						       echo ""
						        echo "→  🎵  B  →  Audio"
							 echo ""
							  echo "→  📝  C  →  Subtitle"
							   echo ""
							    echo ""
							     echo "Tapez A, B ou C et appuyez sur Entrez"
							      echo ""
							       echo ""
							        read -p "→  Votre choix : " choix
								 
								 if [ "$choix" = "A" ] || [ "$choix" = "a" ]; then
									      # ==========================================
									           # ACTION A - MOVIE
										        # ==========================================
											     
											     echo ""
											          echo "Formats disponibles :"
												       echo "ID    EXT   RESOLUTION  FPS | FILESIZE    TBR PROTO | VCODEC    VBR ACODEC"
												            echo "--------------------------------------------------------------------------------"
													         yt-dlp --no-warnings -F "$url" 2>/dev/null | grep -E "^[0-9]+|audio only" | grep -v "Downloading"
														      
														      video_ids=$(yt-dlp --no-warnings -F "$url" 2>/dev/null | grep "mp4" | grep "[0-9]x[0-9]" | awk '{print $1}')
														           
														           if [ -z "$video_ids" ]; then
																            echo ""
																	             echo "ERREUR: Aucun format video trouve"
																		              echo ""
																			               read -p "Voulez-vous forcer le telechargement direct? (oui/non): " continuer
																				                if [ "$continuer" = "oui" ]; then
																							             echo ""
																								                  read -p "Nom du fichier final (ex: video): " nom
																										               echo ""
																											                    echo "Telechargement direct avec curl..."
																													                 curl -L -o "${nom}.mp4" "$url"
																															              if [ $? -eq 0 ] && [ -f "${nom}.mp4" ]; then
																																	                       echo "SUCCES: ${nom}.mp4"
																																			                        exit 0
																																						             else
																																								                      echo "ECHEC: Telechargement impossible"
																																										                       exit 1
																																												                    fi
																																														             else
																																																                  exit 1
																																																		           fi
																																																			        fi
																																																				     
																																																				     best_video_id=$(echo "$video_ids" | sort -n | tail -1)
																																																				          
																																																				          audio_ids=$(yt-dlp --no-warnings -F "$url" 2>/dev/null | grep "audio only" | awk '{print $1}')
																																																					       audio_count=$(echo "$audio_ids" | wc -l)
																																																					            
																																																					            if [ -z "$audio_ids" ]; then
																																																							             echo ""
																																																								              echo "ATTENTION: Aucune piste audio trouvee"
																																																									               echo ""
																																																										                read -p "Voulez-vous continuer sans audio? (oui/non): " continuer
																																																												         if [ "$continuer" != "oui" ]; then
																																																														              exit 1
																																																															               fi
																																																																            fi
																																																																	         
																																																																	         first_audio_id=$(echo "$audio_ids" | head -1)
																																																																		      
																																																																		      echo ""
																																																																		           echo "ID video disponibles:"
																																																																			        
																																																																			        for id in $video_ids; do
																																																																					         # Chercher la taille du fichier
																																																																						          size=$(yt-dlp --no-warnings -F "$url" 2>/dev/null | grep "^[[:space:]]*$id" | grep -oE '[0-9]+(\.[0-9]+)?[GMK]iB' | head -1)
																																																																							           if [ -z "$size" ]; then
																																																																									                size=$(yt-dlp --no-warnings -F "$url" 2>/dev/null | grep "^[[:space:]]*$id" | awk '{for(i=1;i<=NF;i++) if($i ~ /[0-9]+\.[0-9]+[GMK]iB/) print $i}' | head -1)
																																																																											         fi
																																																																												          if [ -z "$size" ]; then
																																																																														               size="taille inconnue"
																																																																															                fi
																																																																																	         
																																																																																	         if [ "$id" = "10942" ]; then
																																																																																			              echo "  ID:$id (1920x1080p - $size)"
																																																																																				               elif [ "$id" = "3120" ]; then
																																																																																						                    echo "  ID:$id (1280x720p - $size)"
																																																																																								             elif [ "$id" = "1094" ]; then
																																																																																										                  echo "  ID:$id (854x480p - $size)"
																																																																																												           elif [ "$id" = "563" ]; then
																																																																																														                echo "  ID:$id (640x360p - $size)"
																																																																																																         elif [ "$id" = "297" ]; then
																																																																																																		              echo "  ID:$id (428x240p - $size)"
																																																																																																			               else
																																																																																																					                    res=$(yt-dlp --no-warnings -F "$url" 2>/dev/null | grep "^[[:space:]]*$id" | grep -oE '[0-9]+x[0-9]+')
																																																																																																							                 if [ -n "$res" ]; then
																																																																																																										                  echo "  ID:$id ($res - $size)"
																																																																																																												               else
																																																																																																														                        echo "  ID:$id ($size)"
																																																																																																																	             fi
																																																																																																																		              fi
																																																																																																																			           done
																																																																																																																				        
																																																																																																																				        while true; do
																																																																																																																						         echo ""
																																																																																																																							          echo "Exemple: $best_video_id"
																																																																																																																								           read -p "Tape un ID : " id_v
																																																																																																																									            
																																																																																																																									            id_valide=0
																																																																																																																										             for id in $video_ids; do
																																																																																																																												                  if [ "$id" = "$id_v" ]; then
																																																																																																																															                   id_valide=1
																																																																																																																																	                    break
																																																																																																																																			                 fi
																																																																																																																																					          done
																																																																																																																																						           
																																																																																																																																						           if [ "$id_valide" -eq 1 ]; then
																																																																																																																																								                break
																																																																																																																																										         else
																																																																																																																																												              echo "ID invalide! Choisis parmi: $video_ids"
																																																																																																																																													               fi
																																																																																																																																														            done
																																																																																																																																															         
																																																																																																																																															         if [ -z "$id_v" ]; then
																																																																																																																																																	          id_v="$best_video_id"
																																																																																																																																																		       fi
																																																																																																																																																		            
																																																																																																																																																		            if [ -n "$audio_ids" ]; then
																																																																																																																																																				             echo ""
																																																																																																																																																					              echo "ID audio disponibles:"
																																																																																																																																																						               
																																																																																																																																																						               for id in $audio_ids; do
																																																																																																																																																								                    if echo "$id" | grep -qi "francais"; then
																																																																																																																																																											                     echo "  ID:$id (Francais)"
																																																																																																																																																													                  elif echo "$id" | grep -qi "english"; then
																																																																																																																																																																                   echo "  ID:$id (English)"
																																																																																																																																																																		                else
																																																																																																																																																																					                 echo "  ID:$id"
																																																																																																																																																																							              fi
																																																																																																																																																																								               done
																																																																																																																																																																									                
																																																																																																																																																																									                while true; do
																																																																																																																																																																												             echo ""
																																																																																																																																																																													                  echo "Exemple: $first_audio_id"
																																																																																																																																																																															               read -p "Tape un ID audio : " id_a1_input
																																																																																																																																																																																                    
																																																																																																																																																																																                    if [ "$id_a1_input" = "bestaudio" ]; then
																																																																																																																																																																																			                     id_a1="bestaudio"
																																																																																																																																																																																					                      break
																																																																																																																																																																																							                   fi
																																																																																																																																																																																									                
																																																																																																																																																																																									                id_valide=0
																																																																																																																																																																																											             for id in $audio_ids; do
																																																																																																																																																																																													                      if [ "$id" = "$id_a1_input" ]; then
																																																																																																																																																																																																                           id_valide=1
																																																																																																																																																																																																			                        break
																																																																																																																																																																																																						                 fi
																																																																																																																																																																																																								              done
																																																																																																																																																																																																									                   
																																																																																																																																																																																																									                   if [ "$id_valide" -eq 1 ]; then
																																																																																																																																																																																																												                    id_a1="$id_a1_input"
																																																																																																																																																																																																														                     break
																																																																																																																																																																																																																                  else
																																																																																																																																																																																																																			                   echo "ID invalide! Choisis parmi: $audio_ids"
																																																																																																																																																																																																																					                fi
																																																																																																																																																																																																																							         done
																																																																																																																																																																																																																								      else
																																																																																																																																																																																																																									               id_a1=""
																																																																																																																																																																																																																										            fi
																																																																																																																																																																																																																											         
																																																																																																																																																																																																																											         echo ""
																																																																																																																																																																																																																												      echo "Exemple: Game of Thrones S01E01"
																																																																																																																																																																																																																												           read -p "Nom du fichier final: " nom
																																																																																																																																																																																																																													        
																																																																																																																																																																																																																													        echo ""
																																																																																																																																																																																																																														     if [ -n "$id_a1" ]; then
																																																																																																																																																																																																																															              echo "Telechargement de ID:$id_v + ID:$id_a1..."
																																																																																																																																																																																																																																               yt-dlp --downloader ffmpeg -f "$id_v+$id_a1" --hls-use-mpegts --merge-output-format mkv -o "${nom}.mkv" "$url"
																																																																																																																																																																																																																																	            else
																																																																																																																																																																																																																																			             echo "Telechargement de ID:$id_v (sans audio)..."
																																																																																																																																																																																																																																				              yt-dlp --downloader ffmpeg -f "$id_v" --hls-use-mpegts -o "${nom}.mkv" "$url"
																																																																																																																																																																																																																																					           fi
																																																																																																																																																																																																																																						        
																																																																																																																																																																																																																																						        if [ $? -ne 0 ] || [ ! -f "${nom}.mkv" ]; then
																																																																																																																																																																																																																																								         echo "ECHEC: le telechargement a echoue"
																																																																																																																																																																																																																																									          exit 1
																																																																																																																																																																																																																																										       fi
																																																																																																																																																																																																																																										            
																																																																																																																																																																																																																																										            echo "SUCCES: ${nom}.mkv"
																																																																																																																																																																																																																																											         
																																																																																																																																																																																																																																											         if [ -n "$audio_ids" ] && [ "$audio_count" -gt 1 ]; then
																																																																																																																																																																																																																																													          current_file="${nom}.mkv"
																																																																																																																																																																																																																																														           current_audio="$id_a1"
																																																																																																																																																																																																																																															            
																																																																																																																																																																																																																																															            while true; do
																																																																																																																																																																																																																																																	                 echo ""
																																																																																																																																																																																																																																																			              read -p "Ajouter une autre piste audio? (oui/non): " autre
																																																																																																																																																																																																																																																				                   if [ "$autre" != "oui" ]; then
																																																																																																																																																																																																																																																							                    break
																																																																																																																																																																																																																																																									                 fi
																																																																																																																																																																																																																																																											              
																																																																																																																																																																																																																																																											              echo ""
																																																																																																																																																																																																																																																												                   echo "ID audio disponibles (excluant deja ajoutes):"
																																																																																																																																																																																																																																																														                for id in $audio_ids; do
																																																																																																																																																																																																																																																																	                 if [ "$id" != "$current_audio" ]; then
																																																																																																																																																																																																																																																																				                      if echo "$id" | grep -qi "francais"; then
																																																																																																																																																																																																																																																																							                               echo "  ID:$id (Francais)"
																																																																																																																																																																																																																																																																										                            elif echo "$id" | grep -qi "english"; then
																																																																																																																																																																																																																																																																														                             echo "  ID:$id (English)"
																																																																																																																																																																																																																																																																																	                          else
																																																																																																																																																																																																																																																																																					                           echo "  ID:$id"
																																																																																																																																																																																																																																																																																								                        fi
																																																																																																																																																																																																																																																																																											                 fi
																																																																																																																																																																																																																																																																																													              done
																																																																																																																																																																																																																																																																																														                   
																																																																																																																																																																																																																																																																																														                   while true; do
																																																																																																																																																																																																																																																																																																	                    read -p "Tape un ID audio: " id_an_input
																																																																																																																																																																																																																																																																																																			                     id_valide=0
																																																																																																																																																																																																																																																																																																					                      for id in $audio_ids; do
																																																																																																																																																																																																																																																																																																								                           if [ "$id" = "$id_an_input" ] && [ "$id" != "$current_audio" ]; then
																																																																																																																																																																																																																																																																																																												                            id_valide=1
																																																																																																																																																																																																																																																																																																															                             break
																																																																																																																																																																																																																																																																																																																		                          fi
																																																																																																																																																																																																																																																																																																																					                   done
																																																																																																																																																																																																																																																																																																																							                    if [ "$id_valide" -eq 1 ]; then
																																																																																																																																																																																																																																																																																																																										                         id_an="$id_an_input"
																																																																																																																																																																																																																																																																																																																													                      break
																																																																																																																																																																																																																																																																																																																															                       else
																																																																																																																																																																																																																																																																																																																																		                            echo "ID invalide ou deja ajoute!"
																																																																																																																																																																																																																																																																																																																																					                     fi
																																																																																																																																																																																																																																																																																																																																							                  done
																																																																																																																																																																																																																																																																																																																																									               
																																																																																																																																																																																																																																																																																																																																									               yt-dlp --downloader ffmpeg -f "$id_an" -o "temp_audio.m4a" "$url"
																																																																																																																																																																																																																																																																																																																																										                    
																																																																																																																																																																																																																																																																																																																																										                    if [ -f "temp_audio.m4a" ]; then
																																																																																																																																																																																																																																																																																																																																													                     mv "$current_file" "temp_video.mkv"
																																																																																																																																																																																																																																																																																																																																															                      ffmpeg -i "temp_video.mkv" -i "temp_audio.m4a" -map 0:v -map 0:a -map 1:a -c copy "${nom}.mkv"
																																																																																																																																																																																																																																																																																																																																																	                       mv "${nom}.mkv" "$current_file"
																																																																																																																																																																																																																																																																																																																																																			                        rm -f temp_video.mkv temp_audio.m4a
																																																																																																																																																																																																																																																																																																																																																						                 current_audio="$current_audio|$id_an"
																																																																																																																																																																																																																																																																																																																																																								                  echo "SUCCES: Nouvelle piste audio ajoutee"
																																																																																																																																																																																																																																																																																																																																																										               else
																																																																																																																																																																																																																																																																																																																																																												                        echo "ECHEC: Impossible de telecharger l'audio"
																																																																																																																																																																																																																																																																																																																																																															             fi
																																																																																																																																																																																																																																																																																																																																																																              done
																																																																																																																																																																																																																																																																																																																																																																	           fi
																																																																																																																																																																																																																																																																																																																																																																		        
																																																																																																																																																																																																																																																																																																																																																																		        echo ""
																																																																																																																																																																																																																																																																																																																																																																			     echo "TERMINE: ${nom}.mkv"
																																																																																																																																																																																																																																																																																																																																																																			          echo "Taille: $(ls -lh "${nom}.mkv" | awk '{print $5}')"
																																																																																																																																																																																																																																																																																																																																																																				   
																																																																																																																																																																																																																																																																																																																																																																				   elif [ "$choix" = "B" ] || [ "$choix" = "b" ]; then
																																																																																																																																																																																																																																																																																																																																																																					        # ==========================================
																																																																																																																																																																																																																																																																																																																																																																						     # ACTION B - AUDIO
																																																																																																																																																																																																																																																																																																																																																																						          # ==========================================
																																																																																																																																																																																																																																																																																																																																																																							       
																																																																																																																																																																																																																																																																																																																																																																							       echo ""
																																																																																																																																																																																																																																																																																																																																																																							            echo "Formats audio disponibles :"
																																																																																																																																																																																																																																																																																																																																																																								         yt-dlp --no-warnings -F "$url" 2>/dev/null | grep "audio only" | grep -v "Downloading"
																																																																																																																																																																																																																																																																																																																																																																									      
																																																																																																																																																																																																																																																																																																																																																																									      audio_ids=$(yt-dlp --no-warnings -F "$url" 2>/dev/null | grep "audio only" | awk '{print $1}')
																																																																																																																																																																																																																																																																																																																																																																									           
																																																																																																																																																																																																																																																																																																																																																																									           if [ -z "$audio_ids" ]; then
																																																																																																																																																																																																																																																																																																																																																																											            echo ""
																																																																																																																																																																																																																																																																																																																																																																												             echo "ERREUR: Aucune piste audio trouvee"
																																																																																																																																																																																																																																																																																																																																																																													              exit 1
																																																																																																																																																																																																																																																																																																																																																																														           fi
																																																																																																																																																																																																																																																																																																																																																																															        
																																																																																																																																																																																																																																																																																																																																																																															        echo ""
																																																																																																																																																																																																																																																																																																																																																																																     echo "ID audio disponibles:"
																																																																																																																																																																																																																																																																																																																																																																																          
																																																																																																																																																																																																																																																																																																																																																																																          for id in $audio_ids; do
																																																																																																																																																																																																																																																																																																																																																																																		           if echo "$id" | grep -qi "francais"; then
																																																																																																																																																																																																																																																																																																																																																																																				                echo "  ID:$id (Francais)"
																																																																																																																																																																																																																																																																																																																																																																																						         elif echo "$id" | grep -qi "english"; then
																																																																																																																																																																																																																																																																																																																																																																																								              echo "  ID:$id (English)"
																																																																																																																																																																																																																																																																																																																																																																																									               else
																																																																																																																																																																																																																																																																																																																																																																																											                    echo "  ID:$id"
																																																																																																																																																																																																																																																																																																																																																																																													             fi
																																																																																																																																																																																																																																																																																																																																																																																														          done
																																																																																																																																																																																																																																																																																																																																																																																															       
																																																																																																																																																																																																																																																																																																																																																																																															       first_audio_id=$(echo "$audio_ids" | head -1)
																																																																																																																																																																																																																																																																																																																																																																																															            
																																																																																																																																																																																																																																																																																																																																																																																															            while true; do
																																																																																																																																																																																																																																																																																																																																																																																																	             echo ""
																																																																																																																																																																																																																																																																																																																																																																																																		              echo "Exemple: $first_audio_id"
																																																																																																																																																																																																																																																																																																																																																																																																			               read -p "Tape un ID audio : " id_a1_input
																																																																																																																																																																																																																																																																																																																																																																																																				                
																																																																																																																																																																																																																																																																																																																																																																																																				                id_valide=0
																																																																																																																																																																																																																																																																																																																																																																																																						         for id in $audio_ids; do
																																																																																																																																																																																																																																																																																																																																																																																																								              if [ "$id" = "$id_a1_input" ]; then
																																																																																																																																																																																																																																																																																																																																																																																																										                       id_valide=1
																																																																																																																																																																																																																																																																																																																																																																																																												                        break
																																																																																																																																																																																																																																																																																																																																																																																																															             fi
																																																																																																																																																																																																																																																																																																																																																																																																																              done
																																																																																																																																																																																																																																																																																																																																																																																																																	               
																																																																																																																																																																																																																																																																																																																																																																																																																	               if [ "$id_valide" -eq 1 ]; then
																																																																																																																																																																																																																																																																																																																																																																																																																			                    id_a1="$id_a1_input"
																																																																																																																																																																																																																																																																																																																																																																																																																					                 break
																																																																																																																																																																																																																																																																																																																																																																																																																							          else
																																																																																																																																																																																																																																																																																																																																																																																																																									               echo "ID invalide! Choisis parmi: $audio_ids"
																																																																																																																																																																																																																																																																																																																																																																																																																										                fi
																																																																																																																																																																																																																																																																																																																																																																																																																												     done
																																																																																																																																																																																																																																																																																																																																																																																																																												          
																																																																																																																																																																																																																																																																																																																																																																																																																												          echo ""
																																																																																																																																																																																																																																																																																																																																																																																																																													       read -p "Nom du fichier audio (ex: son.m4a): " nom_audio
																																																																																																																																																																																																																																																																																																																																																																																																																													            
																																																																																																																																																																																																																																																																																																																																																																																																																													            echo ""
																																																																																																																																																																																																																																																																																																																																																																																																																														         echo "Telechargement de ID:$id_a1..."
																																																																																																																																																																																																																																																																																																																																																																																																																															      yt-dlp --downloader ffmpeg -f "$id_a1" -o "${nom_audio}" "$url"
																																																																																																																																																																																																																																																																																																																																																																																																																															           
																																																																																																																																																																																																																																																																																																																																																																																																																															           if [ $? -eq 0 ] && [ -f "${nom_audio}" ]; then
																																																																																																																																																																																																																																																																																																																																																																																																																																	            echo "SUCCES: ${nom_audio}"
																																																																																																																																																																																																																																																																																																																																																																																																																																		         else
																																																																																																																																																																																																																																																																																																																																																																																																																																				          echo "ECHEC: le telechargement a echoue"
																																																																																																																																																																																																																																																																																																																																																																																																																																					           exit 1
																																																																																																																																																																																																																																																																																																																																																																																																																																						        fi
																																																																																																																																																																																																																																																																																																																																																																																																																																							 
																																																																																																																																																																																																																																																																																																																																																																																																																																							 elif [ "$choix" = "C" ] || [ "$choix" = "c" ]; then
																																																																																																																																																																																																																																																																																																																																																																																																																																								      # ==========================================
																																																																																																																																																																																																																																																																																																																																																																																																																																								           # ACTION C - SOUS-TITRES
																																																																																																																																																																																																																																																																																																																																																																																																																																									        # ==========================================
																																																																																																																																																																																																																																																																																																																																																																																																																																										     
																																																																																																																																																																																																																																																																																																																																																																																																																																										     echo ""
																																																																																																																																																																																																																																																																																																																																																																																																																																										          echo "Langues de sous-titres disponibles:"
																																																																																																																																																																																																																																																																																																																																																																																																																																											       yt-dlp --no-warnings --list-subs "$url" 2>/dev/null | grep -v "Downloading"
																																																																																																																																																																																																																																																																																																																																																																																																																																											            
																																																																																																																																																																																																																																																																																																																																																																																																																																											            echo ""
																																																																																																																																																																																																																																																																																																																																																																																																																																												         read -p "Tape le code langue (ex: fr, en) ou 'all': " subs_lang
																																																																																																																																																																																																																																																																																																																																																																																																																																													      
																																																																																																																																																																																																																																																																																																																																																																																																																																													      if [ -n "$subs_lang" ]; then
																																																																																																																																																																																																																																																																																																																																																																																																																																														               echo ""
																																																																																																																																																																																																																																																																																																																																																																																																																																															                echo "Telechargement des sous-titres..."
																																																																																																																																																																																																																																																																																																																																																																																																																																																	         
																																																																																																																																																																																																																																																																																																																																																																																																																																																	         if [ "$subs_lang" = "all" ]; then
																																																																																																																																																																																																																																																																																																																																																																																																																																																			              yt-dlp --skip-download --write-sub --sub-lang all -o "%(title)s" "$url"
																																																																																																																																																																																																																																																																																																																																																																																																																																																				               else
																																																																																																																																																																																																																																																																																																																																																																																																																																																						                    yt-dlp --skip-download --write-sub --sub-lang "$subs_lang" -o "%(title)s" "$url"
																																																																																																																																																																																																																																																																																																																																																																																																																																																								             fi
																																																																																																																																																																																																																																																																																																																																																																																																																																																									              
																																																																																																																																																																																																																																																																																																																																																																																																																																																									              if [ $? -eq 0 ]; then
																																																																																																																																																																																																																																																																																																																																																																																																																																																											                   echo "SUCCES: Sous-titres telecharges"
																																																																																																																																																																																																																																																																																																																																																																																																																																																													            else
																																																																																																																																																																																																																																																																																																																																																																																																																																																															                 echo "ECHEC: Impossible de telecharger"
																																																																																																																																																																																																																																																																																																																																																																																																																																																																	          fi
																																																																																																																																																																																																																																																																																																																																																																																																																																																																		       else
																																																																																																																																																																																																																																																																																																																																																																																																																																																																			                echo "ECHEC: Aucune langue selectionnee"
																																																																																																																																																																																																																																																																																																																																																																																																																																																																					     fi
																																																																																																																																																																																																																																																																																																																																																																																																																																																																					      
																																																																																																																																																																																																																																																																																																																																																																																																																																																																					      else
																																																																																																																																																																																																																																																																																																																																																																																																																																																																						           echo "Option invalide"
																																																																																																																																																																																																																																																																																																																																																																																																																																																																							    fi
